---
# Use Ansible Galaxy to install dependencies
dependency:
  name: galaxy
  options:
    # Install required galaxy roles
    role-file: ../../requirements.yml
    # Install required collections
    requirements-file: ../../requirements.yml

# Run molecule inside of a docker container
driver:
  name: docker

platforms:
  - name: ubuntu_package_manager
    image: "geerlingguy/docker-ubuntu2204-ansible:latest"
    # Setting the command to this is necessary for systemd containers
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

  - name: kali_package_manager
    image: cisagov/docker-kali-ansible:latest
    # Setting the command to this is necessary for systemd containers
    command: ""
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  env:
    ANSIBLE_CALLBACK_PLUGINS: "${MOLECULE_SCENARIO_DIRECTORY}/callback_plugins"
  # Uncomment for verbose output
  # env:
  #   ANSIBLE_VERBOSITY: 3

verifier:
  name: ansible
